package edu.bjtu.android.entity;

import java.io.Serializable;
import java.util.Date;

public class Material implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.course_id
     *
     * @mbg.generated
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.mediatype
     *
     * @mbg.generated
     */
    private String mediatype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.material_type
     *
     * @mbg.generated
     */
    private String materialType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.material_url
     *
     * @mbg.generated
     */
    private String materialUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table material
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.id
     *
     * @return the value of material.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.id
     *
     * @param id the value for material.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.course_id
     *
     * @return the value of material.course_id
     *
     * @mbg.generated
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.course_id
     *
     * @param courseId the value for material.course_id
     *
     * @mbg.generated
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.mediatype
     *
     * @return the value of material.mediatype
     *
     * @mbg.generated
     */
    public String getMediatype() {
        return mediatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.mediatype
     *
     * @param mediatype the value for material.mediatype
     *
     * @mbg.generated
     */
    public void setMediatype(String mediatype) {
        this.mediatype = mediatype == null ? null : mediatype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.material_type
     *
     * @return the value of material.material_type
     *
     * @mbg.generated
     */
    public String getMaterialType() {
        return materialType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.material_type
     *
     * @param materialType the value for material.material_type
     *
     * @mbg.generated
     */
    public void setMaterialType(String materialType) {
        this.materialType = materialType == null ? null : materialType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.material_url
     *
     * @return the value of material.material_url
     *
     * @mbg.generated
     */
    public String getMaterialUrl() {
        return materialUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.material_url
     *
     * @param materialUrl the value for material.material_url
     *
     * @mbg.generated
     */
    public void setMaterialUrl(String materialUrl) {
        this.materialUrl = materialUrl == null ? null : materialUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.create_date
     *
     * @return the value of material.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.create_date
     *
     * @param createDate the value for material.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.description
     *
     * @return the value of material.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.description
     *
     * @param description the value for material.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.status
     *
     * @return the value of material.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.status
     *
     * @param status the value for material.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", courseId=").append(courseId);
        sb.append(", mediatype=").append(mediatype);
        sb.append(", materialType=").append(materialType);
        sb.append(", materialUrl=").append(materialUrl);
        sb.append(", createDate=").append(createDate);
        sb.append(", description=").append(description);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}